UnitreeGO1Cfg:
  loop_frequency: 500
  joint_names:
    - "abad_L_Joint"
    - "abad_R_Joint"
    - "hip_L_Joint"
    - "hip_R_Joint"
    - "knee_L_Joint"
    - "knee_R_Joint"
  
  init_state:
    # target angles [rad] when action = 0.0
    default_joint_angle:
      abad_L_Joint: 0.0
      abad_R_Joint: 0.0
      hip_L_Joint: 0.0918
      hip_R_Joint: 0.0918
      knee_L_Joint: -0.057
      knee_R_Joint: -0.057

  control:
    # PD Drive parameters:
    stiffness: 40.0
    damping: 2.5
    action_scale_pos: 0.25
    decimation: 4 # 10.0
    user_torque_limit: 60

  normalization:
    clip_scales:
      clip_observations: 100.
      clip_actions: 100.
    obs_scales:
      lin_vel: 1.0
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 1.0

  size:
    actions_size: 6
    observations_size: 32 # 27
    observations_history_length: 5 # 1
    latent_size: 64
    commands_size: 3

  stand_mode:
    stand_duration: 1.0

  imu_orientation_offset:
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  user_cmd_scales:
    lin_vel_x: 1.0
    lin_vel_y: 1.0
    ang_vel_yaw: 1.0
